apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  type: {{ .Values.service.type }}  # Adjust based on values.yaml (LoadBalancer, ClusterIP, etc.)
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}  # Adjust based on values.yaml (external port)
    targetPort: 5000  # Target port within the container
