
replicaCount: 1

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

spec:
  containers:
    - name: flask-app
      image:
        repository: zezo001/flask-app
        tag: latest
      ports: 
        - containerPort: 5000