# values.yaml
image:
  repository: zezo001/flask-app  # Replace with your actual image repository
  tag: latest

# Resources (optional, use defaults if not needed)
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

# Service configuration (optional, use defaults if not needed)
service:
  type: LoadBalancer  # Adjust based on your access needs (e.g., ClusterIP)
  port: 5000
  targetPort: 5000

# Replica count (optional, use default of 1 if not needed)
replicaCount: 1
